### ISSUE TITLE
hard dependency on python 3.7?

### ISSUE THREAD

**Issue by vincer** [globality-corp/microcosm-pubsub#133]
```
(pubsub) ✔ [11:17] /tmp λ python
Python 3.6.5 (default, Mar 29 2018, 00:00:00)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from microcosm_pubsub.result import MessageHandlingResult
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/tmp/pubsub/lib/python3.6/site-packages/microcosm_pubsub/result.py", line 5, in <module>
    from dataclasses import dataclass, field
ModuleNotFoundError: No module named 'dataclasses'

(pubsub) ✘ [11:15] /tmp λ pip freeze |grep pubsub
microcosm-pubsub==1.13.0
```

Starting with 1.12 there's now a dependency on `dataclasses` which is new as of 3.7.

If this is intended, can `python_requires='>=3.7',` be added to setup.py so that pip does the right thing?

**Comment by jessemyers** [comment]
Good idea: https://github.com/globality-corp/microcosm-pubsub/pull/134

**Comment by vincer** [comment]
Cool.

Of course, it'd be nice to have 3.6 compatibility as that's what we're using and it I'd like us to be keep up with your new versions. 

Is microcosm in general dropping 3.6 compatibility? Currently we don't have a lot driving us to move to 3.7, so this would definitely be a new factor.

**Comment by jessemyers** [comment]
It's a bit murky. We're using 3.7 internally, but this is the first place we've let that leak into `microcosm`. We're likely to move forward with 3.7isms elsewhere _eventually_, but it's not an urgent thing for us.

**Comment by vincer** [comment]
If you don't mind unsolicited advice... deciding where to draw the line for python version support is a bit murky, but only supporting 3.7 seems a bit drastic since it was only released 4 months ago. At least supporting 3.6 (released 12/2016) opens up the potential `microcosm` audience significantly.

(Granted, this is a bit self-serving as we're on 3.6...)

FWIW, there is a [backport of dataclasses](https://pypi.org/project/dataclasses/), so with an `install_requires` [env marker](https://www.python.org/dev/peps/pep-0508/#environment-markers) we should be able to make everyone happy in this particular case.

`dataclasses;python_version<"3.7"`

**Comment by jessemyers** [comment]
Makes sense, sure.

**Comment by jessemyers** [comment]
Should be addressed in `1.15.0`

Retaining Python 3.6 as a minimum version to support f-strings

**Comment by vincer** [comment]
🎉 Thanks for the quick turn around!

(Also, how did I not know about f-strings? My world view just shifted...)

**Comment by jessemyers** [comment]
Yeah, f-strings are pretty hard to do without once you start using them.
